name: Backup volumes from docker-compose.yml

on:
  schedule:
    - cron: '0 0 * * *' # daily at 0:00
  workflow_dispatch:

concurrency:
  group: backup-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backup:
    uses: mahn-ke/.github/.github/workflows/template-backup.yml@main
    secrets: inherit